# Generated by Django 4.1.7 on 2023-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0002_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_perfil',
            field=models.CharField(default='', max_length=100),
        ),
    ]
