# Generated by Django 4.1.7 on 2023-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_alter_aluno_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto_perfil',
            field=models.CharField(default='/static/media/foto_perfil_default.png', max_length=100),
        ),
    ]
